language: r
os: linux
dist: xenial

r:
  - release
  - bioc-devel
  - bioc-release

cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library

notifications:
  slack:
    rooms:
      - cognitivediso-4tq7056:brFd4sbtS9GoLSjYuyoHuAus#biopathnet

install:
  - R -e "renv::restore()"
  - R -e "install.packages('devtools')"

script:
  - R -e "devtools::check()"
